#!/usr/bin/env bash
set -euo pipefail
python3 -m py_compile proxy/nexus_proxy.py
node tests/node-mode-tests.js
node tests/syntax-check.js
node tests/catalog-paths-tests.js
node tests/local-script-refs-tests.js
node tests/sandbox-policy-tests.js
node tests/subscription-burst-tests.js
node tests/wallet-handshake-tests.js
node tests/block-contract-tests.js
node tests/companion-block-tests.js
node tests/verse-block-tests.js
node tests/breed-engine-tests.js
node tests/battle-engine-tests.js
node tests/pokemon-engine-tests.js
node tests/router-battle-tests.js
node tests/os-battle-tests.js
node tests/cross-block-tests.js
node tests/palette-tests.js
node tests/eventlog-tests.js
node tests/system-health-tests.js
node tests/notification-center-tests.js
node tests/player-thread-tests.js
node tests/sweep13-regression-tests.js
node tests/sweep14-polish-tests.js
node tests/sweep15-living-forge-tests.js
node tests/sweep16-first-hour-tests.js
node tests/sweep20-eidolon-forge-tests.js
node tests/undo-tests.js
node tests/deadletter-tests.js
node tests/roadmap-status-tests.js
node tests/battle-protocol-tests.js
node tests/slot-economy-tests.js
node tests/battle-stakes-tests.js
node tests/witness-tests.js
node tests/imprint-tests.js
node tests/tools-tests.js
node tests/protocol-harness.js
