from __future__ import annotations

from pathlib import Path
from typing import Any

from .util import atomic_write_text, load_json


def render_status_markdown(status: dict[str, Any]) -> str:
    target = status.get("canonical_target")
    target_text = "None"
    if target:
        target_text = f"`{target.get('tag')}` / `{target.get('commit')}` / `{target.get('snapshot_sha256')}`"
    tasks = status.get("active_tasks") or []
    blocks = status.get("assurance_blocks") or []
    return f"""# Nexus status\n\n> Generated from `STATUS.json`. Do not edit this file by hand.\n\n| Field | Value |\n|---|---|\n| Lab | `{status.get('lab_id')}` |\n| Round | `{status.get('current_round')}` |\n| Mode | `{status.get('current_mode')}` |\n| Canonical target | {target_text} |\n| Open defect blocks | `{status.get('open_defect_blocks', 0)}` |\n| Open assurance blocks | `{status.get('open_assurance_blocks', 0)}` |\n| Last completed action | `{status.get('last_completed_action')}` |\n| Next action | `{status.get('next_action_id')}` |\n\n## Active tasks\n\n{''.join(f'- `{x}`\n' for x in tasks) or '- None\n'}\n## Assurance blocks\n\n{''.join(f'- `{x}`\n' for x in blocks) or '- None\n'}"""


def render_status_file(root: Path) -> Path:
    status = load_json(root / "STATUS.json")
    output = root / "STATUS.md"
    atomic_write_text(output, render_status_markdown(status))
    return output
