from __future__ import annotations

from pathlib import Path
from typing import Any

from .util import NexusError, atomic_write_text, load_json

ASSURANCE_MODES = {"BLOCK", "WARN", "ADVISORY"}
ALWAYS_AVAILABLE_COMMANDS = {
    "status",
    "next",
    "doctor",
    "verify",
    "audit-check",
    "exchange-verify",
    "exchange-ledger-check",
    "shadow-verify",
    "cold-consumer-check",
    "pcx-value-check",
    "pcx-convergence-check",
    "pcx-store-audit",
}


def _normalise_assurance_block(raw: Any) -> dict[str, Any]:
    """Return one assurance block in the typed v2 shape.

    Legacy string blocks remain readable as advisory records. They are deliberately
    not promoted into hard gates because a string contains no command scope or
    override semantics.
    """
    if isinstance(raw, str):
        if not raw.strip():
            raise NexusError("Assurance block identifiers cannot be empty.")
        return {
            "id": raw,
            "mode": "ADVISORY",
            "commands": [],
            "reason": "Legacy untyped assurance block; visible but not executable.",
            "legacy": True,
        }
    if not isinstance(raw, dict):
        raise NexusError("Each assurance block must be a string or object.")

    block_id = str(raw.get("id", "")).strip()
    mode = str(raw.get("mode", "")).upper().strip()
    reason = str(raw.get("reason", "")).strip()
    commands = raw.get("commands", [])

    if not block_id:
        raise NexusError("Typed assurance blocks require a non-empty id.")
    if mode not in ASSURANCE_MODES:
        raise NexusError(f"Assurance block {block_id!r} has invalid mode {mode!r}.")
    if not isinstance(commands, list) or any(not isinstance(item, str) or not item for item in commands):
        raise NexusError(f"Assurance block {block_id!r} commands must be a list of non-empty strings.")
    if mode in {"BLOCK", "WARN"} and not commands:
        raise NexusError(f"Assurance block {block_id!r} mode {mode} requires command scope.")
    if not reason:
        raise NexusError(f"Assurance block {block_id!r} requires a reason.")

    return {
        "id": block_id,
        "mode": mode,
        "commands": commands,
        "reason": reason,
        "legacy": False,
    }


def assurance_decision(status: dict[str, Any], command: str) -> dict[str, Any]:
    """Evaluate typed assurance policy for one CLI command.

    Core inspection commands remain available even when mutation is blocked, so an
    operator can always inspect status and diagnose the reason for a stop.
    """
    blocks = [_normalise_assurance_block(item) for item in status.get("assurance_blocks") or []]
    advisory = [block for block in blocks if block["mode"] == "ADVISORY"]
    blocked: list[dict[str, Any]] = []
    warnings: list[dict[str, Any]] = []

    if command not in ALWAYS_AVAILABLE_COMMANDS:
        for block in blocks:
            if block["mode"] == "ADVISORY":
                continue
            if command not in block["commands"] and "*" not in block["commands"]:
                continue
            if block["mode"] == "BLOCK":
                blocked.append(block)
            elif block["mode"] == "WARN":
                warnings.append(block)

    return {
        "schema": "nexus.assurance-decision/v1",
        "command": command,
        "status": "BLOCKED" if blocked else "WARN" if warnings else "PASS",
        "blocked": blocked,
        "warnings": warnings,
        "advisory": advisory,
    }


def enforce_assurance_blocks(root: Path, command: str) -> dict[str, Any]:
    decision = assurance_decision(load_json(root / "STATUS.json"), command)
    if decision["blocked"]:
        details = "; ".join(f"{item['id']}: {item['reason']}" for item in decision["blocked"])
        raise NexusError(f"Assurance gate blocked `{command}`. {details}")
    return decision


def render_status_markdown(status: dict[str, Any]) -> str:
    target = status.get("canonical_target")
    target_text = "None"
    if target:
        target_text = f"`{target.get('tag')}` / `{target.get('commit')}` / `{target.get('snapshot_sha256')}`"
    tasks = status.get("active_tasks") or []
    blocks = [_normalise_assurance_block(item) for item in status.get("assurance_blocks") or []]

    task_text = "".join(f"- `{item}`\n" for item in tasks) or "- None\n"
    block_lines: list[str] = []
    for block in blocks:
        scope = ", ".join(f"`{command}`" for command in block["commands"]) or "none"
        legacy = "; legacy/untyped" if block["legacy"] else ""
        block_lines.append(
            f"- `{block['id']}` — **{block['mode']}** — commands: {scope}{legacy} — {block['reason']}\n"
        )
    block_text = "".join(block_lines) or "- None\n"

    return f"""# Nexus status

> Generated from `STATUS.json`. Do not edit this file by hand.

| Field | Value |
|---|---|
| Lab | `{status.get('lab_id')}` |
| Round | `{status.get('current_round')}` |
| Mode | `{status.get('current_mode')}` |
| Canonical target | {target_text} |
| Open defect blocks | `{status.get('open_defect_blocks', 0)}` |
| Open assurance blocks | `{status.get('open_assurance_blocks', 0)}` |
| Last completed action | `{status.get('last_completed_action')}` |
| Next action | `{status.get('next_action_id')}` |

## Active tasks

{task_text}
## Assurance blocks

{block_text}"""


def render_status_file(root: Path) -> Path:
    status = load_json(root / "STATUS.json")
    output = root / "STATUS.md"
    atomic_write_text(output, render_status_markdown(status))
    return output
